### ISSUE TITLE
Update DurableTask in API to use UserLongRunningTokenCredential to make API calls

### ISSUE THREAD

**Issue by colbylwilliams** [microsoft/developer-platform#40]
Currently the [`DurableTaskClaimsPrincipalExtensions`](src/Microsoft.Developer.DurableTasks/DurableTaskClaimsPrincipalExtensions.cs) is serializing the `ClaimsPrincipal` into a tag for use by an activity later in the orchestration.  The principle has sensitive information, so it shouldn't be included in durable task's task hub storage.  Instead PR #38 introduces a mechanism to use `Microsoft.Identity's` built-in support for long running session keys.  This removes the burden of persisting the entire principle for use later, utilizes `Microsoft.Identity` distributed token cache, and will handle things like token refresh.

**Comment by twsouthwick** [comment]
is this still necessary with the plan you mentioned to remove the orchestration?

**Comment by colbylwilliams** [comment]
Probably not.  Hold on implementing until we think through the orchestration changes.

**Comment by twsouthwick** [comment]
This is no longer necessary as we're going a different direction
