### ISSUE TITLE
PostEntityReturns202 test failing intermittently in CI

### ISSUE THREAD

**Issue by colbylwilliams** [microsoft/developer-platform#41]
[PostEntityReturns202](https://github.com/microsoft/developer-platform/blob/main/tests/Microsoft.Developer.Api.Tests/EntitiesApiTests.cs#L169) failing intermittently in CI.  Having trouble figuring out the issue, as I can't get it to fail locally.

Examples:

https://github.com/microsoft/developer-platform/actions/runs/7503319098/job/20427829171
https://github.com/microsoft/developer-platform/actions/runs/7489243886/job/20385373052
https://github.com/microsoft/developer-platform/actions/runs/7478768860/job/20354445679

**Comment by twsouthwick** [comment]
Similar to #40, is this still necessary given the plan to cut the orchestration part?

**Comment by colbylwilliams** [comment]
Probably not, let's hold on this.

**Comment by colbylwilliams** [comment]
@twsouthwick actually we should at least disable/remove it for now.  It's [preventing our release](https://github.com/microsoft/developer-platform/actions/runs/7560537162/job/20586786145) pipeline from running.
