### ISSUE TITLE
Add Provider ID to EntityRef

### ISSUE THREAD

**Issue by colbylwilliams** [microsoft/developer-platform#43]
### EntityRef

```
{kind}:[{namespace}/]{name}
```
becomes 
```
{kind}:{provider}/[{namespace}/]{name}
```

- `provider` == the provider id, (e.g. devcenter.azure.com) and is required
- `namespace` is optional, and defaults to `"default"` when not provided (same as current behavior)

### API

Obviously this changes the platform's API endpoints.

These stay the same (and their functionality doesn't change)
- `/entities`
- `/entities/{kind}`

But
- `/entities/{kind}/{namespace}/{name}` becomes `/entities/{kind}/{provider}/{namespace}/{name}`

I **don't** think we implement a `/entities/{kind}/{provider}` endpoint (at least not as part of this issue).  I consider that a part of the search/filter story.

### Why?

- The platform assumes EntityRef's are globally unique, and there's not a good way to enforce that among multiple providers
- The platform isn't caching the association between entityref <-> provider, so it's (inefficiently) calling all providers for a single entity, and requiring `providerId` in the payload for template create calls

### 1. Do the API endpoints that the providers implement also change?

No. Since the `provider` segment in the EntityRef is essentially a routing key to know which registered provider url to call, it **must** match the `id` of a provider registration.  It should (and currently is) written on each entity's metadata object by the platform.

The platform API gets a request to `/entities/{kind}/{provider}/{namespace}/{name}` and then calls `/entities/{kind}/{namespace}/{name}` on the specified provider.

**Comment by colbylwilliams** [comment]
As part of this and https://github.com/microsoft/developer-platform/issues/45#issuecomment-1898872252 moving POST to the specific entity path, we need to handle the `Location` header when the provider returns one by:

1. replacing the host of the provider with the host to the platform,  and
2. inject the provider id into the path to the entity.

For example:

```mermaid
sequenceDiagram
    % autonumber
    actor user as User
    participant api as Platform
    participant provider as Provider

    user->>api: POST /entities/template/{provider}/{ns}/{name}
    api->>+provider: POST /entities/template/{ns}/{name}

    provider->>-api: 202 <br/>Retry-After: 1<br/>Location: /entities/operation/{ns}/{name}
    api->>user: 202 Accepted<br/>Retry-After: 1<br/>Location: /entities/operation/{provider}/{ns}/{name}
```

**Comment by twsouthwick** [comment]
moving the location header to a separate issue

**Comment by twsouthwick** [comment]
In order for this to be required, a provider will need to know its own id to be able to construct an entity ref to itself.

For example the functions sample does this:

```csharp
[Function(nameof(GetEntity))]
public async Task<IActionResult> GetEntity(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "entities/{kind}/{namespace}/{name}")] HttpRequest req,
    string kind, string @namespace, string name, CancellationToken token)
{
    var entityRef = new EntityRef(kind) { Provider = /* NEED PROVIDER */ Name = name, Namespace = @namespace };
    ...
}
```

A provider currently does not have a way to supply this value which we want to be required. I see two ways to handle this:

1. Have a magic string, such as `SELF` that would be replaced by the framework

  ```csharp
  var entityRef = new EntityRef(kind) { Provider = EntityProvider.Self, Name = name, Namespace = @namespace };
  ```

3. Pass a header (or some other mechanism) to the provider to tell it its own provider id in the system.

  ```csharp
  [Function(nameof(GetEntity))]
public async Task<IActionResult> GetEntity(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "entities/{kind}/{namespace}/{name}")] HttpRequest req,
    [FromHeader(Name = "X-DEVELOPER-PLATFORM-PROVIDERID")] string provider, string kind, string @namespace, string name, CancellationToken token)
{
    var entityRef = new EntityRef(kind) { Provider = provider, Name = name, Namespace = @namespace };
    ...
}
  ```

I believe (2) will be the simplest and most straightforward with less "magic". @colbylwilliams - thoughts? other ideas?

**Comment by colbylwilliams** [comment]
Let's go with option 2 (header)
