### ISSUE TITLE
Use Entity with `kind:Operation` for long-running and remove DurableTask from platform

### ISSUE THREAD

**Issue by colbylwilliams** [microsoft/developer-platform#45]
Currently most of the orchestration is (must be) handled by the providers, so let's remove the durable task orchestration logic from the platform and make it a more standard API.  If we find that the platform itself needs more orchestration logic, we should be able to use the provider model to add that functionality.

This includes removing the `/status` endpoint for the API

Operation entity would look something like this:

```json
{
  "apiVersion": "developer.microsoft.com/v1",
  "kind": "Operation",
  "metadata": {
    "name": "79ff4e1eef0c456b80192a01aeacba26",
    "namespace": "sample",
    "provider": "sample.functions"
  },
  "spec": {
    "user": "User:foobar@microsoft.com",
    "created": "2024-01-16T23:04:01.81854+00:00",
    "state": "Running",
    "updated": "2024-01-16T23:04:02.761792+00:00"
  }
}
```

**Comment by twsouthwick** [comment]
So will the API still be `POST /entities` with the `kind:Operation` as the payload?

**Comment by twsouthwick** [comment]
Per offline discussion:

- We'll change the payload body to be just the template spec

**Comment by twsouthwick** [comment]
As I look at this change, I'll probably do it in the following steps:

- [ ] Remove the durable tasks infra for POST and replace with API (the GET will still cycle through all the providers to find what we need)
- [ ] Add the `providerId` to the `GET` APIs for the API and remove the shared `MapGet` now that we'll have different APIs these enable
- [ ] Additional clean up to remove now unnecessary things

**Comment by twsouthwick** [comment]
Tracking the larger feature in #53
